-- Compatibility note:
-- Customer SCD Type 2 is now batch-scoped and is implemented together with
-- incremental fact loading in 5_incremental_load.sql.
-- Use scripts/3_run_transformations.py <batch_id> to execute it safely.
